environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm bower
  - npm install
  - bower install

build: off

test_script:
  - node --version
  - npm --version
  - bower --version
  - npm test
